name: Salesforce CI/CD

on:
  push:
    branches:
      - QA

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli
          sfdx --version

      - name: Authenticate Salesforce
        run: |
          echo "${{ secrets.SF_SERVER_KEY }}" > server.key
          sfdx auth jwt grant --client-id ${{ secrets.SF_CONSUMER_KEY }} \
            --jwt-key-file server.key --username ${{ secrets.SF_USERNAME }} --set-default-dev-hub

      - name: Deploy to Salesforce
        run: |
          cd $GITHUB_WORKSPACE
          sfdx force:source:deploy -p force-app -u ${{ secrets.SF_USERNAME }} --wait 10

      - name: Run Apex Tests
        run: |
          sfdx force:apex:test:run --codecoverage --resultformat human --wait 10
