name: Deploy to Salesforce QA

on:
  push:
    branches:
      - QA  # This triggers only on pushes to the QA branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Root Files
        run: ls -la

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli
          sfdx --version

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SF_SERVER_KEY }}" > server.key
          sfdx auth jwt grant --client-id "${{ secrets.SF_CONSUMER_KEY }}" \
          --jwt-key-file server.key --username "${{ secrets.SF_USERNAME }}" \
          --setdefaultusername

      - name: List Authenticated Orgs
        run: sfdx force:org:list

      - name: Deploy to Salesforce
        working-directory: MyProject
        run: sfdx force:source:deploy -p force-app -w 10
