name: Salesforce QA Deployment

on:
  push:
    branches:
      - QA

env:
  SFDX_CLIENT_ID: ${{ secrets.SF_CONSUMER_KEY }}
  SFDX_CLIENT_SECRET: ${{ secrets.SF_CONSUMER_SECRET_KEY }}
  SFDX_USERNAME: ${{ secrets.SF_USERNAME }}
  SFDX_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir ~/sfdx
          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          
      - name: Install SFDX Git Delta Plugin
        run: echo y | sfdx plugins:install sfdx-git-delta
        
      - name: Authorize Salesforce Org
        run: |
          echo "${SFDX_CLIENT_ID}" > client_id.txt
          sfdx auth:jwt:grant --clientid $(cat client_id.txt) --jwtkeyfile server.key --username ${SFDX_USERNAME} --instanceurl ${SFDX_INSTANCE_URL} -a targetorg
          
      - name: Deploy to Org
        run: sfdx force:source:deploy -p force-app/main/default -u targetorg --json
        
      - name: Handle Deployment Error
        if: failure()
        run: |
          echo "Deployment failed. Check the deployment status and logs above."
          exit 1
